<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>Eternal Sunshine of the Endless Flight  &middot; Statistics @ Home</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">
<meta name="viewport" content="width=device-width, initial-scale=1">


<meta name="description" content="I am sitting on a plane from Rome to Philadelphia, marveling at how quickly we can move around the globe. There is a 6 hour time-zone difference between Rome and Philadelphia. My flight took off at 11am in Rome and was set to arrive 9 hours and 45 minutes later at 3:45pm in Philadelphia. This got me thinking, what would your daily schedule look like if you continuously flew west?" />

<meta name="keywords" content="key, words, ">


<meta property="og:title" content="Eternal Sunshine of the Endless Flight  &middot; Statistics @ Home ">
<meta property="og:site_name" content="Statistics @ Home"/>
<meta property="og:url" content="/2017/06/12/eternal-sunshine-of-the-endless-flight/" />
<meta property="og:locale" content="en-EN">


<meta property="og:type" content="article" />
<meta property="og:description" content="I am sitting on a plane from Rome to Philadelphia, marveling at how quickly we can move around the globe. There is a 6 hour time-zone difference between Rome and Philadelphia. My flight took off at 11am in Rome and was set to arrive 9 hours and 45 minutes later at 3:45pm in Philadelphia. This got me thinking, what would your daily schedule look like if you continuously flew west?"/>
<meta property="og:article:published_time" content="2017-06-12T00:00:00Z" />
<meta property="og:article:modified_time" content="2017-06-12T00:00:00Z" />

  
    
<meta property="og:article:tag" content="key">
    
<meta property="og:article:tag" content="words">
    
  

  
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@inschool4life" />
<meta name="twitter:creator" content="@inschool4life" />
<meta name="twitter:title" content="Eternal Sunshine of the Endless Flight" />
<meta name="twitter:description" content="I am sitting on a plane from Rome to Philadelphia, marveling at how quickly we can move around the globe. There is a 6 hour time-zone difference between Rome and Philadelphia. My flight took off at 11am in Rome and was set to arrive 9 hours and 45 minutes later at 3:45pm in Philadelphia. This got me thinking, what would your daily schedule look like if you continuously flew west?" />
<meta name="twitter:url" content="/2017/06/12/eternal-sunshine-of-the-endless-flight/" />
<meta name="twitter:domain" content="/">
  

<script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "Article",
    "headline": "Eternal Sunshine of the Endless Flight",
    "author": {
      "@type": "Person",
      "name": "http://profiles.google.com/+?rel=author"
    },
    "datePublished": "2017-06-12",
    "description": "I am sitting on a plane from Rome to Philadelphia, marveling at how quickly we can move around the globe. There is a 6 hour time-zone difference between Rome and Philadelphia. My flight took off at 11am in Rome and was set to arrive 9 hours and 45 minutes later at 3:45pm in Philadelphia. This got me thinking, what would your daily schedule look like if you continuously flew west?",
    "wordCount": 554
  }
</script>



<link rel="canonical" href="/2017/06/12/eternal-sunshine-of-the-endless-flight/" />

<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/touch-icon-144-precomposed.png">
<link href="/favicon.png" rel="icon">

<meta name="generator" content="Hugo 0.26" />

  
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

<link href='https://fonts.googleapis.com/css?family=Merriweather:300%7CRaleway%7COpen+Sans' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="/css/font-awesome.min.css">
<link rel="stylesheet" href="/css/style.css">
<link rel="stylesheet" href="/css/highlight/default.css">

  <script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    skipTags: ['script', 'noscript', 'style', 'textarea', 'pre']
  }
});
</script>
<script async type="text/javascript"
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
  
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-102259122-1', 'auto');
	  ga('send', 'pageview');

	</script>

</head>
<body>
  <main id="main-wrapper" class="container main_wrapper has-sidebar">
    <header id="main-header" class="container main_header">
  <div class="container brand">
  <div class="container title h1-like">
  <a class="baselink" href="/">
  Statistics @ Home

</a>

</div>

  
<div class="container topline">
  
  statistics from the home of two statisticians


</div>


</div>

  <nav class="container nav primary no-print">
  

<a class="homelink" href="/">home</a>


  
<a href="/about">about</a>

<a href="/post" title="Show list of posts">posts</a>

<a href="/tags" title="Show list of tags">tags</a>


</nav>

<div class="container nav secondary no-print">
  
<a id="contact-link-email" class="contact_link" href="mailto:stats.at.home@gmail.com">
  <span class="fa fa-envelope-square"></span><span>email</span></a>



<a id="contact-link-github" class="contact_link" href="https://github.com/jsilve24">
  <span class="fa fa-github-square"></span><span>github</span></a>











<a id="contact-link-twitter" class="contact_link" href="https://twitter.com/inschool4life">
  <span class="fa fa-twitter-square"></span><span>twitter</span></a>













</div>


  

</header>


<article id="main-content" class="container main_content single">
  <header class="container hat">
  <h1>Eternal Sunshine of the Endless Flight
</h1>

  <div class="metas">
<time datetime="2017-06-12">12 Jun, 2017</time>


  
    &middot; by Justin Silverman
  
  &middot; Read in about 3 min
  &middot; (554 Words)
  <br>
  


</div>

</header>

  <div class="container content">
  <!-- BLOGDOWN-HEAD -->
<!-- /BLOGDOWN-HEAD -->

<!-- BLOGDOWN-BODY-BEFORE -->
<!-- /BLOGDOWN-BODY-BEFORE -->
<p>I am sitting on a plane from Rome to Philadelphia, marveling at how quickly we can move around the globe. There is a 6 hour time-zone difference between Rome and Philadelphia. My flight took off at 11am in Rome and was set to arrive 9 hours and 45 minutes later at 3:45pm in Philadelphia. This got me thinking, what would your daily schedule look like if you continuously flew west?</p>
<p>My calculations are based on gross approximations from the information given in the seatback display in front of me. For example, I am assuming that you could fly continuously forever, and I am assuming that the rate at which my flight is changing time-zones would be representative. We will also not take seasonal changes into account and assume a 12 hour day/night cycle.</p>
<div id="stupid-simple-calculations" class="section level1">
<h1>Stupid simple calculations</h1>
<p>First, I am going to calculate the effective rate at which time is progressing for me in the air (relative to the day/night cycles for someone fixed on the ground).</p>
<pre class="r"><code>effective.rate &lt;- (15.75-11.00)/9.75
(effective.rate*60)</code></pre>
<pre><code>## [1] 29.23077</code></pre>
<p>That is, for every hour that passes on the ground (with respect to day/night cycles), I experience only 29.23 minutes of progression in the day/night cycle.</p>
<p>Since there are no appreciable relativistic effects occuring at 858 kilometers/hour (our speed according to the display), we can say that I experience the passage of 1 hour identically to the experience of someone remaining in the same location on the ground. In that way, I do not feel that 1 hour feels longer or shorter while in flight. Now I will calculate the number of hours it would take to experience a full day/night cycle when traveling at this rate.</p>
<pre class="r"><code>(24/effective.rate)</code></pre>
<pre><code>## [1] 49.26316</code></pre>
<p>Therefore the passage of one full day/night cycle would take about 49.26 hours or that day/night would each last about <span class="math inline">\(24.63\)</span> hours.</p>
<p>Thats a pretty long day.</p>
</div>
<div id="a-little-farther" class="section level1">
<h1>A little farther</h1>
<p>I have long said that my internal clock is acctually a 26 hour schedule. Effectively, if left to my own devices, I tend to go to bed about 2 hours later every night and wake up 2 hours later every morning (doing a full cycle every 12 days). So what speed must I be traveling west at to achieve this desired 26 hour day?</p>
<p>I will start by calculating the time it takes to cross 1 time-zone and the resulting estimate for the average number of kilometers per time-zone during my trip.</p>
<pre class="r"><code>current.speed &lt;- 858 # kilometers per hour
(km.per.tz &lt;- (9.75/6)*current.speed) #(hours in flight/time zone difference)*current speed</code></pre>
<pre><code>## [1] 1394.25</code></pre>
<pre class="r"><code>desired.cycle.length &lt;- 26
(1-24/desired.cycle.length)*km.per.tz</code></pre>
<pre><code>## [1] 107.25</code></pre>
<p>Therefore, if I traveled west at about 107.25 km/h my day would appear to be 26 hours long.</p>
<p>These calculations are not completely correct but I am guessing I am within about 25% of the correct result based on <a href="https://physics.stackexchange.com/questions/187730/how-fast-would-one-have-to-travel-in-an-airplane-in-order-to-experience-a-contin">this physics stackexchange post</a>. Under certain conditions they calculate that at the equator traveling at 1672.2 km/h would allow you to track the sunset. I find that you would have to travel at 1394.25 which is 0.83% of their answer.</p>
<p>My approximation would likely be much better if I considered that my flight was not at the equator and that my speed and direction (velocity) was not constant throughout the entirety of the flight.</p>
<p>Either way I find this an interesting thought experiment.</p>
</div>

</div>


  <footer class="container">
  <div class="container navigation no-print">
  <h2>Navigation</h2>
  
  

    
    <a class="prev" href="/2017/06/07/fitting-non-linear-groth-curves-in-r/" title="Fitting Non-Linear Growth Curves in R">
      Previous
    </a>
    

    
    <a class="next" href="/2017/06/26/measure-theory-made-ridiculously-simple/" title="Measure Theory Made Ridiculously Simple">
      Next
    </a>
    

  


</div>

  <div class="container comments">
  <h2>Comments</h2>
  
<div id="disqus_thread"></div>
<script type="text/javascript">
  (function() {
    
    
    if (window.location.hostname == "localhost")
      return;

    var dsq = document.createElement('script'); dsq.async = true; dsq.type = 'text/javascript';
    dsq.src = '//statistics-home.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>


</div>

</footer>

</article>
      <footer id="main-footer" class="container main_footer">
  

  <div class="container nav foot no-print">
  

  <a class="toplink" href="#">back to top</a>

</div>

  <div class="container credits">
  
<div class="container footline">
  

</div>


  
<div class="container copyright">
  
  &copy; 2017 Justin and Rachel Silverman


</div>


</div>

</footer>

    </main>
    
<script type="text/javascript">
  (function() {
    
    
    if (window.location.hostname == "localhost")
      return;

    var dsq = document.createElement('script'); dsq.async = true; dsq.type = 'text/javascript';
    dsq.src = '//statistics-home.disqus.com/count.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>



<script src="/js/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>


    
  </body>
</html>

